### ISSUE TITLE
false positives for phantom types

### ISSUE THREAD

**Issue by michaelglass** [jfmengels/review-unused#11] opened 2020-01-20 16:42 UTC
Sometimes we're using custom type without their constructors, e.g. https://medium.com/@ckoster22/advanced-types-in-elm-phantom-types-808044c5946d
cc @arkham

When that's the case, we get warnings to remove the constructors.

I'm not aware of a nice workaround besides having maybe control comments, e.g. -- "elm-review: allow-phantom-type" or something

```elm
module Main exposing (func)


type PhantomType
    = PhantomType


type OtherPhantomType
    = OtherPhantomType -- this comment tells elm-review to allow phantom types


type PhantomTypeContainer a
    = PhantomTypeContainer -- this comment tells elm-review to allow phantom types


phantomTypeFour : PhantomTypeContainer PhantomType -> Number
phantomTypeFour _ =
    4


otherPhantomTypeOlive : PhantomTypeContainer OtherPhantomType -> String
otherPhantomTypeOlive _ =
    "olive"


init : PhantomTypeContainer a
init =
    PhantomTypeContainer


main =
    phantomTypeFour init + String.length (otherPhantomTypeOlive init)
```

**Comment by jfmengels** [comment] 2020-01-20 18:01
Hi @michaelglass :)

I think the usual solution to this that tools use is, to use warning comments, but I find that to be a no-so-great solution, as ideally, we would like this to be done automatically for us, and we shouldn't have to please "that tool that is annoying in this case but is otherwise very useful".

`elm-review` doesn't allow you to ignore errors that get reported, which is done by design.

Also, at the moment `elm-review` doesn't allow looking at comments, but that's something I have overviewed, I should add that ability.

## Proposed solution

I think we could not report constructors of a type, if the type itself is used as a phantom type variable. I consider a phantom type variable (just to clarify the vocabular I am using here) to be the `a` in `type Foo a = Foo`, where `a` is never used anywhere in the type's constructors.

I think we can make things work like that, while still reporting unused constructors for cases where it's not supposed to be used as a phantom type. 

Additional constraints I am considering, but I don't know if they make things too constraining or confusing:
- It only has one type constructor - I have never seen one with multiple, and I don't see why it would
- The type constructor has no arguments - I have never seen one with arguments, and I don't see why it would

I would love feedback on this, so let me know what you think.

## `elm-review` shortcomings

Even though , `elm-review` doesn't have the capability to determine if a type has a phantom type variable, if it comes from a different file. I am actively working on making that possible, and it will be released in a future major version, for which I have no ETA.

## Temporary solution

In the meantime, you could solve the problem using a record as the phantom type variable, like this for instance

```elm
phantomTypeFour : PhantomTypeContainer { phantomType : () } -> Number
phantomTypeFour _ =
    4


otherPhantomTypeOlive : PhantomTypeContainer { otherPhantomType : () } -> String
otherPhantomTypeOlive _ =
    "olive"
```

**Comment by michaelglass** [comment] 2020-01-20 18:16
> It only has one type constructor
I agree

> The type constructor has no arguments
We have some with arguments but ... not necessarily for any good reason. I think it's fine to suggest we don't.

**Comment by jfmengels** [comment] 2020-04-20 13:52
@michaelglass This has been released in the latest version of the package, compatible with `elm-review` v2.

The rule now detects when a type variable corresponds to a phantom variable. It only does this for the first level, meaning if the type variable never appears in the type's definition.

```elm
type Id a = Id

userId : Id User

type User = User -- considered used
```

In the future it will be able to do a better job, because it will look at whether the types for which it finds the type variable it finds is itself a phantom variable, and recursively. Example:


```elm
type Id a = Id

type alias Thing a =
  { id : Id a
  }

type User = User -- considered not used, but it could

user : Thing User
user = { id : Id }
```

I don't know when I'll get to that, and I welcome help!
In the meantime, there is a way to configure the rule to handle all cases :+1:

**Closed as completed by jfmengels** 2020-04-20 13:52 UTC
